DEPENDENCIES: {}
DISABLED_COGS: []

GUILD_IDS:
  DEV: null
  MOC: null

# ======= TOKENS =========

TOKENS:
  PRODUCTION: null
  DEVELOPMENT: null

# ======= API/SERVER CONNECTIONS =========
API_URL: "http://API_URL/"
API_KEY: null

SOCKET:
  HOST: 127.0.0.1
  PORT: 1234
  KEY: null

LAVALINK:
  HOST: 127.0.0.1
  PORT: 1234
  PASS: null

SPOTIFY:
  CLIENT_ID: null
  CLIENT_SECRET: null

# ======= LOGGING =========

LOGGING:
  {
    "version": 1,
    "formatters":
      {
        "standard":
          {
            "format": "%(asctime)s %(levelname)-6s %(name)-15s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
          },
        "ColouredFormatter":
          { "()": "utils.ColouredFormatter.ColouredFormatter" },
      },
    "handlers":
      {
        "file":
          {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "standard",
            "level": "DEBUG",
            "filename": "logs/latest.log",
            "mode": "w",
            "maxBytes": 100000,
            "backupCount": 5,
          },
        "stdout":
          {
            "class": "logging.StreamHandler",
            "formatter": "ColouredFormatter",
            "level": "INFO",
            "stream": "ext://sys.stdout",
          },
      },
    "loggers":
      {
        "":
          {
            "level": "DEBUG",
            "handlers": ["file", "stdout"],
            "propagate": False,
          },
      },
  }
