server:
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
plugins:
  youtube:
    enabled: true
    remoteCipher:
      url: "http://service-yt-cipher:8001"
      # Comment out the above line and uncomment the line below for local running in your application.yaml.local
      # url: "http://yt-cipher:8001"
    oauth:
      enabled: true
      refreshToken: ${LAVALINK_REFRESH_TOKEN}
      # On first time setup, set this to false and do not set a refreshToken. Lavalink will provide instructions on
      # how to obtain a refreshToken.
      skipInitialization: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEB
      - TV
      - MWEB
      - ANDROID_VR
      - TVHTML5_SIMPLY
      - WEBEMBEDDED
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      youtube: false
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      countryCode: "AU"
    youtube:
      countryCode: "AU"
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO
